#####################################################################
# Automatically generated by qtpromaker
#####################################################################

TEMPLATE = app
TARGET = tmp

SOURCES *= \
    ./testEndlPerformance.cpp

OTHER_FILES +=file.txt
